#!/usr/bin/env bash

# The token is retrieved from http://127.0.0.1:8080/manage/configureSecurity under "Git plugin notifyCommit access tokens"
# If somehow the token is lost, you can revoke and get another token from UI, and use it in here instead.
curl "http://127.0.0.1:8081/git/notifyCommit?url=file:///var/jenkins_home/repo&token=691e7ddc92f431e04b6224e5a424dda0"

