pipeline {
    agent {
        docker {
            image 'docker.io/golang:1.22.3'
            args '-H unix:///run/user/1001/docker.sock -v /home/jenkins/agent/repo:${WORKSPACE}/repo'
        }
    }

    options {
        skipDefaultCheckout()
    }

    triggers {
        pollSCM('')
    }

    stages {
        stage('Checkout') {
            steps {
                sh 'if [ ! -d ${WORKSPACE}/repo ]; then exit 1; else echo "Checkout successful."; fi'
            }
        }

        stage('CI') {
            steps {
                dir('repo/src') {
                    sh 'go version'
                }
            }
        }
    }
}
