pipeline {
    agent {
        label "default"
    }

    options {
        skipDefaultCheckout()
    }

    triggers {
        pollSCM('')
    }

    environment {
        TIMEOUT="sleep 900"
        BUILD_IMAGE="docker.io/library/golang:1.22.3"
        EXEC="podman exec -it ${BUILD_TAG}"
    }

    stages {
        stage('Checkout') {
            steps {
                sh 'cp -r /home/jenkins/agent/repo ${WORKSPACE}/repo'
                sh 'if [ ! -d ${WORKSPACE}/repo ]; then exit 1; else echo "Checkout successful."; fi'
            }
        }

        stage('Start build container') {
            steps {
                sh 'podman run -d --name ${BUILD_TAG} -w /ci -v ${WORKSPACE}/repo:/ci $BUILD_IMAGE $TIMEOUT'
                sh 'if [ -n $(podman ps --filter "status=exited" --filter "status=unknown" --noheading | wc -l) ]; then exit 1; else echo "Container ${BUILD_TAG} is started successfully."; fi'
            }
        }

        stage('Run unit tests') {
            steps {
                sh '$EXEC go test'
            }
        }
    }
}
